language: csharp
mono: none
dotnet: 2.1.300
dist: trusty
branches:
  only:
   - master
install:
 - dotnet restore
script:
 - dotnet build
 - dotnet test -c Release test/unit/Http.Query.Filter.Test/Http.Query.Filter.Test.csproj