language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 3.0

branches:
  only:
    - master

install:
  - dotnet tool install --global Cake.Tool --version 0.35.0
  - export PATH=$PATH:$HOME/.dotnet/tools

script:
  - dotnet cake
